#define O_RDONLY  0x000
#define O_WRONLY  0x001
#define O_RDWR    0x002
#define O_CREATE  0x200
// Rhugaved edits
#define CLONE_FILES 1
#define CLONE_FS 2
#define CLONE_PARENT 4
#define CLONE_VM 8
#define CLONE_THREAD 16